name: cc-indicators
channels:
  - conda-forge

dependencies:
  - python=3.12

  # Core
  - numpy
  - pandas
  - scipy
  - xarray
  - matplotlib
  - netcdf4
  - dask
  - h5netcdf

  # Geospatial
  - cartopy
  - geopandas
  - contextily
  - cmocean

  # Visualization
  - plotly
  - anywidget
  - seaborn

  # Web
  - requests

  # Notebook
  - ipykernel

  - pip
  - pip:
      - kaleido
      - df2img
      - myst-nb
      - copernicusmarine
      - great-tables
      - playwright