name: deploy-book

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Solo si necesitas añadir matrix_cc a extra
      # - name: Copy custom HTML content
      #   run: |
      #     mkdir -p _build/html/extra
      #     cp -r matrix_cc _build/html/extra/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
