name: deploy-book

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy built HTML from repo
        run: |
          cp -r _build/html deploy

      - name: List contents
        run: ls -R deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "deploy"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4